IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='VersiuniDB')
BEGIN
	ALTER TABLE VersiuniDB DROP CONSTRAINT FK_do
	ALTER TABLE VersiuniDB DROP CONSTRAINT FK_undo
	DROP TABLE ComenziSQL
	DROP TABLE VersiuniBD
	PRINT 'deleted ComenziSQL'
END

CREATE TABLE ComenziSQL(
	id INT PRIMARY KEY IDENTITY,
	sqlstring NVARCHAR(500) NOT NULL,
)

CREATE TABLE VersiuniBD(
	id INT PRIMARY KEY IDENTITY,
	versiune INT NOT NULL,
	is_current BIT NOT NULL DEFAULT 0,
	do_id INT,
	undo_id INT,
	CONSTRAINT FK_do FOREIGN KEY(do_id) REFERENCES ComenziSQL(id),
	CONSTRAINT FK_undo FOREIGN KEY(undo_id) REFERENCES ComenziSQL(id),
)


IF NOT EXISTS(SELECT * FROM VersiuniBD)
	INSERT INTO VersiuniBD(versiune, is_current, do_id, undo_id) VALUES(0, 1, NULL, NULL)