# Generated by Django 4.0.6 on 2022-07-14 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='latitude',
            field=models.DecimalField(decimal_places=8, max_digits=11),
        ),
        migrations.AlterField(
            model_name='info',
            name='lognitude',
            field=models.DecimalField(decimal_places=8, max_digits=11),
        ),
    ]
