# Generated by Django 4.0.6 on 2022-07-20 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_lognitude_info_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(choices=[('Triunghi', 'Triunghi'), ('Patrulater', 'Patrulater'), ('Cerc', 'Cerc')], default='Triunghi', max_length=15)),
                ('puncte', models.TextField(default='0 0\n0 0\n0 0')),
            ],
        ),
        migrations.CreateModel(
            name='OwnSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nrrecalcpoz', models.IntegerField(default=3, verbose_name='Numarul de relocari')),
                ('secafterrecalc', models.IntegerField(default=60, verbose_name='Numarul de secunde dupa care este disponibila o relocare')),
            ],
        ),
        migrations.AlterField(
            model_name='info',
            name='nrcalcloc',
            field=models.IntegerField(blank=True, default=1, verbose_name='Numarul de relocari'),
        ),
        migrations.AlterField(
            model_name='info',
            name='text',
            field=models.TextField(blank=True, max_length=300, verbose_name='observatie'),
        ),
    ]
