# Generated by Django 4.0.6 on 2022-07-20 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_ownsettings_forme'),
    ]

    operations = [
        migrations.AddField(
            model_name='forma',
            name='nume',
            field=models.CharField(blank=True, default='corp', max_length=10),
        ),
    ]
