# Generated by Django 4.0.6 on 2022-07-21 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_ownsettings_disterror'),
    ]

    operations = [
        migrations.CreateModel(
            name='Harta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(blank=True, default='Harta', max_length=15)),
                ('adresa', models.CharField(blank=True, default='https://www.google.com/maps/dir/^^lat^^,^^long^^//@^^lat^^,^^long^^,21z', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='forma',
            name='puncte',
            field=models.TextField(default='0 0\n0 0'),
        ),
        migrations.AlterField(
            model_name='forma',
            name='tip',
            field=models.CharField(choices=[('Cerc', 'Cerc')], default='Triunghi', max_length=15),
        ),
        migrations.AddField(
            model_name='ownsettings',
            name='harta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.harta'),
        ),
    ]
