# Generated by Django 4.0.6 on 2022-07-23 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_harta_alter_forma_puncte_alter_forma_tip_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comanda',
            options={'verbose_name_plural': 'Comenzi'},
        ),
        migrations.AlterModelOptions(
            name='forma',
            options={'verbose_name': 'Arie pe harta', 'verbose_name_plural': 'Arii pe harta'},
        ),
        migrations.AlterModelOptions(
            name='harta',
            options={'verbose_name_plural': 'Harti'},
        ),
        migrations.AlterModelOptions(
            name='iesire',
            options={'verbose_name_plural': 'Iesiri'},
        ),
        migrations.AlterModelOptions(
            name='intrare',
            options={'verbose_name_plural': 'Intrari'},
        ),
        migrations.AlterModelOptions(
            name='ownsettings',
            options={'verbose_name': 'Setari proprii', 'verbose_name_plural': 'Setari'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Utilizator', 'verbose_name_plural': 'Utilizatori'},
        ),
        migrations.AlterField(
            model_name='info',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11),
        ),
        migrations.AlterField(
            model_name='info',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11),
        ),
    ]
