# Generated by Django 4.0.6 on 2022-07-28 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_ownsettings_min_tolerated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forma',
            name='tip',
            field=models.CharField(choices=[('Cerc', 'Cerc')], default='Cerc', max_length=15),
        ),
        migrations.AlterField(
            model_name='info',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
