# Generated by Django 4.0.6 on 2022-08-09 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_lucru'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownsettings',
            name='datalist_comanda',
            field=models.TextField(blank=True, verbose_name='Lista denumire comenzi'),
        ),
        migrations.AddField(
            model_name='ownsettings',
            name='datalist_lucru',
            field=models.TextField(blank=True, verbose_name='Lista denumire lucrari'),
        ),
    ]
