CREATE OR ALTER FUNCTION ValidDate(@d INT, @m INT, @y INT, @h INT, @min INT) RETURNS VARCHAR(MAX) AS
BEGIN
	DECLARE @rez VARCHAR(MAX) = FORMAT(@d, '00') + '.' + FORMAT(@m, '00') + '.' + FORMAT(@y, '0000') + ' ' +
								FORMAT(@h, '00') + ':' + FORMAT(@min, '00')
	IF TRY_CONVERT(DATETIME, @rez, 104) IS NULL
		RETURN NULL
	RETURN @rez
END

GO
CREATE OR ALTER FUNCTION StrToDate(@str VARCHAR(MAX)) RETURNS DATETIME AS
BEGIN
	RETURN CONVERT(DATETIME, @str, 104)
END