version: '3.9'

services:
  database:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build: ./backend/cause-connect
    ports:
      - "8080:8080"
    environment:
        - JDBC_DATABASE_URL=jdbc:postgresql://database:5432/postgres
        - JDBC_DATABASE_USERNAME=postgres
        - JDBC_DATABASE_PASSWORD=postgres
        - IMAGE_BASE_PATH=/images/
    depends_on:
      - database

volumes:
    postgres-data: { }

networks:
    default:
      name: cause-connect-network