CREATE TABLE Echipe(
	id INT PRIMARY KEY IDENTITY,
	nume NVARCHAR(MAX) NOT NULL,
)

CREATE TABLE Elev(
	id INT PRIMARY KEY IDENTITY,
	nume NVARCHAR(MAX) NOT NULL,
	scoala NVARCHAR(MAX) NOT NULL,
)

CREATE TABLE Jucator(
	idElev INT PRIMARY KEY REFERENCES Elev(id) ON DELETE CASCADE ON UPDATE CASCADE,
	idEchipa INT NOT NULL FOREIGN KEY REFERENCES Echipe(id),
)

CREATE TABLE Meci(
	id INT PRIMARY KEY IDENTITY,
	idEchipa1 INT FOREIGN KEY REFERENCES Echipe(id),
	idEchipa2 INT FOREIGN KEY REFERENCES Echipe(id),
	data DATETIME,
)

CREATE TABLE JucatorActiv(
	idJucator INT FOREIGN KEY REFERENCES Jucator(idElev) ON DELETE CASCADE ON UPDATE CASCADE,
	idMeci INT FOREIGN KEY REFERENCES Meci(id),
	CONSTRAINT PK_JucatorActiv PRIMARY KEY(idJucator, idMeci), 
	nrPuncteInscrise INT DEFAULT 0,
	tip INT,
)

-- helper table
CREATE TABLE SugestiiNumeElevi(
	id INT PRIMARY KEY IDENTITY,
	nume NVARCHAR(MAX) NOT NULL,
	CONSTRAINT CK_nume CHECK (nume NOT LIKE '[^A-Za-z ]')
)