# Generated by Django 4.0.6 on 2022-07-14 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_info_latitude_alter_info_lognitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('info_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.info')),
                ('numar_comanda', models.CharField(default='Cxxxx.xx', max_length=15)),
                ('denumire', models.CharField(default='', max_length=20)),
            ],
            bases=('main.info',),
        ),
        migrations.CreateModel(
            name='Iesire',
            fields=[
                ('info_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.info')),
            ],
            bases=('main.info',),
        ),
        migrations.CreateModel(
            name='Intrare',
            fields=[
                ('info_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.info')),
            ],
            bases=('main.info',),
        ),
        migrations.RenameField(
            model_name='info',
            old_name='observatie',
            new_name='text',
        ),
    ]
