# Generated by Django 4.0.6 on 2022-07-14 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_comanda_iesire_intrare_rename_observatie_info_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='time',
            new_name='datetime',
        ),
    ]
