# Generated by Django 4.0.6 on 2022-07-15 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_time_info_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='nrcalcloc',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
