# Generated by Django 4.0.6 on 2022-07-15 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_info_nrcalcloc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='lognitude',
            new_name='longitude',
        ),
    ]
