# Generated by Django 4.0.6 on 2022-07-20 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_forma_ownsettings_alter_info_nrcalcloc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownsettings',
            name='forme',
            field=models.ManyToManyField(to='main.forma'),
        ),
    ]
