# Generated by Django 4.0.6 on 2022-07-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_comanda_options_alter_forma_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownsettings',
            name='min_tolerated',
            field=models.IntegerField(default=5, verbose_name='Numarul de minute tolerate in calculul celor 8 ore dintre intrare si iesire'),
        ),
    ]
