IF TYPE_ID('String') IS NULL 
	CREATE TYPE String FROM NVARCHAR(30) NULL
DROP FUNCTION udf_TableExists;
GO

CREATE FUNCTION udf_TableExists(@tablename String)
RETURNS BIT AS
BEGIN
	IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME=@tablename)
		RETURN 1
	RETURN 0
END